on:
  push:
    branches:
      - main

on:
  pull_request:
    branches:
      - main
      - 'release'
      - 'release/*'
      - 'release-*'
  check_run:
    types: [rerequested, requested_action]
  push:
    branches:
      - main
      - 'release'
      - 'release/*'
      - 'release-*'
  workflow_dispatch:

env:
  NODE_VERSION: 16.14.2
  NPM_VERSION: 8.15.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node ${{env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
       node-version: ${{env.NODE_VERSION}}
    - name: Use Npm ${{env.NPM_VERSION}}
      run: npm i -g npm@${{env.NPM_VERSION}}
    - run: npm i -g @vscode/vsce
    - run: npm ci
    - run: npm run package
    - uses: actions/upload-artifact@v3
      with:
        name: 'ms-toolsai-jupyter-hub-insiders.vsix'
        path: 'ms-toolsai-jupyter-hub-insiders.vsix'

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node ${{env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
       node-version: ${{env.NODE_VERSION}}
    - name: Use Npm ${{env.NPM_VERSION}}
      run: npm i -g npm@${{env.NPM_VERSION}}
    - run: npm ci
    - run: npm run lint

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node ${{env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
       node-version: ${{env.NODE_VERSION}}
    - name: Use Npm ${{env.NPM_VERSION}}
      run: npm i -g npm@${{env.NPM_VERSION}}
    - run: npm i -g @vscode/vsce
    - run: npm ci
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
